apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mockoon-pvc
  namespace: mockoon1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi