apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockoon
  namespace: mockoon1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockoon
  template:
    metadata:
      labels:
        app: mockoon
    spec:
      containers:
        - name: mockoon
          image: mockoon/cli:2.2.1
          args: ["-d", "/environment/environment.json"]
          volumeMounts:
            - name: environment
              mountPath: "/environment"
            - name: azurefileshare
              mountPath: /responses
      volumes:
        - name: environment
          configMap:
            name: mockoon
        - name: azurefileshare
          azureFile:
            secretName: mockoon
            shareName: responses
            readOnly: false
      restartPolicy: Always


    


# Error: This file is not a valid OpenAPI specification (JSON or YAML v2.0.0 and v3.0.0) or Mockoon environment: EISDIR: illegal operation on a directory, read


#